# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: zkp.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tzkp.proto\x12\x03zkp\"-\n\x13RegistrationRequest\x12\n\n\x02y1\x18\x01 \x01(\x05\x12\n\n\x02y2\x18\x02 \x01(\x05\"\'\n\x14RegistrationResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"-\n\x15\x41uthenticationRequest\x12\t\n\x01r\x18\x01 \x01(\x05\x12\t\n\x01z\x18\x02 \x01(\x05\")\n\x16\x41uthenticationResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\x93\x01\n\x03ZKP\x12\x41\n\x08Register\x12\x18.zkp.RegistrationRequest\x1a\x19.zkp.RegistrationResponse\"\x00\x12I\n\x0c\x41uthenticate\x12\x1a.zkp.AuthenticationRequest\x1a\x1b.zkp.AuthenticationResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'zkp_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REGISTRATIONREQUEST._serialized_start=18
  _REGISTRATIONREQUEST._serialized_end=63
  _REGISTRATIONRESPONSE._serialized_start=65
  _REGISTRATIONRESPONSE._serialized_end=104
  _AUTHENTICATIONREQUEST._serialized_start=106
  _AUTHENTICATIONREQUEST._serialized_end=151
  _AUTHENTICATIONRESPONSE._serialized_start=153
  _AUTHENTICATIONRESPONSE._serialized_end=194
  _ZKP._serialized_start=197
  _ZKP._serialized_end=344
# @@protoc_insertion_point(module_scope)
